### ISSUE TITLE
Introduce FreePlane integration

### ISSUE THREAD

**Issue by dukov** [dukov/silverkey2#1]
Support Import/Export of FreePlane file format

**Comment by dukov** [comment]
Look into WebAssembly. Compile FreePlane app to wasm and use FreePlane plugins/scripts to communicate with Electron

**Comment by metacoma** [comment]
ATM I working on GRPC plugin for Freeplane https://github.com/metacoma/freeplane_plugin_grpc 
This plugins allows to call functions inside running Freeplane application using  gRPC network protocol. 
Regarding this issue, I'll add new gRPC function, to export (serializing) the current opened mindamp as JSON/XML document.

I’ll keep you posted.

**Comment by dukov** [comment]
The idea was revised. Freeplane opened with exec and key value DB swithched to Freeplane MindMap format
